### PR TITLE
Link to #matrix-static on https://view.matrix.org

### PR DESCRIPTION
**Pull request by pdurbin**

### CODE REVIEW

**Comment by ara4n** [comment]
thanks!

**Comment by ara4n** [comment]
i think the right solution for this is actually to reenable view.matrix.org support on matrix.to, so the existing hyperlink there gives the option of reading the room on view.matrix.org. We disabled this whilst view.matrix was offline for a few months, but i've now re-added it. therefore if you look at https://matrix.to/#/#matrix-static:matrix.org you should hopefully (once caching clears) see a link to https://view.matrix.org as desired. I think the explicit link is probably redundant in the readme, so going to close (sorry :/)

**Comment by pdurbin** [comment]
@ara4n thanks for the speedy turn around on my pull request. At https://matrix.to/#/#matrix-static:matrix.org this is what I see:

Screenshot from 2019-09-15 20-22-07

> a link to https://view.matrix.org as desired

Are you talking about the "Access #matrix-static:matrix.org" column? Thanks.

**Comment by ara4n** [comment]
yup, i'm talking about the link in the second row and final column. matrix.to's UX is... minimal though :/

**Pull request closed without merging**
